version: "2"
services:
  influxdb:
    container_name: influxdb
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb:/var/lib/influxdb
      - ./conf/influxdb:/etc/influxdb/
    restart: always

  telegraf:
    container_name: telegraf
    image: telegraf
    network_mode: "host"
    volumes:
      - ./conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  grafana:
    image: grafana/grafana:6.0.0
    network_mode: 'host'
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    user: '0'
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://localhost:3000

  mysql:
    container_name: mysql
    environment:
      MYSQL_DATABASE: grafana
      MYSQL_PASSWORD: grafana
      MYSQL_ROOT_PASSWORD: grafana
      MYSQL_USER: grafana
    image: mariadb
    ports:
      - "3306:3306/tcp"
    restart: unless-stopped
    volumes:
      - /var/lib/docker/mysql:/var/lib/mysql

  mqtt:
    container_name: mqtt
    network_mode: "host"
    image: eclipse-mosquitto:latest
#    user: "demo"
    ports:
      - "1883:1883/tcp"
      - "9001:9001"
    volumes:
      - ./conf/mqtt/mosquitto/:/mosquitto/config/
      - ./conf/mqtt/mosquitto/passswd:/etc/mosquitto/pwfile
      - ./data/mqtt/:/mosquitto/data/
      - ./log/mqtt/:/mosquitto/log/
    restart: always
